# BooruBot Deletion Configuration
# This file contains the list of tags to automatically delete and their reasons

deletions:
  # Tag : Reason for deletion
  "fayanna -status:deleted": "Character requested removal."
