services:
  db:
    image: postgres:10.5
    restart: "no"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=boorubot_db
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "boorubot_db", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5438:5432"
    volumes:
      - .local/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: no
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: kenwood364@gmail.com
      PGADMIN_DEFAULT_PASSWORD: iamnotacrook
    volumes:
      - .local/pgadmin:/var/lib/pgadmin

  boorubot:
    image: boorubot:$TAG
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: America/New_York
      BOT_TOKEN: ""
      ALERT_CHAN_ID: ""
      SERVICE_CHAN_ID: ""
      BOORU_KEY: ""
      BOORU_USER: "DiscordBot"
      BOORU_URL: "https://booru.kitsunehosting.net"
      BOORU_AUTO_UPLOAD: ""
      BOORU_MAINTENANCE: ""
      SAUCENAO_API_KEY: ""
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: boorubot_db
      DB_HOST: db
      DB_PORT: 5432
    volumes:
      - .local/config:/app/config
    restart: "no"
    command: "true"
